### ISSUE TITLE
Question on radio saving song titles

### ISSUE THREAD

**Issue by waxfingers** [donmaiq/mpv-scripts#1]
First off, must say that despite the scarce documentation I find your scripts well thought out and super useful THANK YOU +)

Secondly, and regarding the radio lua script: would it be possible to toogle a "keep saving automaticly" the songs' info as they change throughout the session?

Also, is there a way to have more than one radio station (in the playlist, or several playlists) and cycle through them?

Cheers

**Comment by jonniek** [comment]
Thanks for the good suggestion. I implemented it in 1e5640d37cda3c0950a92696af420fe651d3d0c2  

You can have unlimited stations, one URL per line in the playlistfile. Cycling through them works like any other playlist in mpv. If you only need one station you can write it directly on the settings playlist variable instead of a file.

Any particular part of the documentation I should improve upon or just in general?

Glad you found my scripts useful.

**Comment by waxfingers** [comment]
F A N T A S T I C !!!

It now feels "complete" 'cause being you also behind playlistmanager (another great plugin/script) there's this coherent navigating and visual feedback; can change directly to any of my fav radio stations on the fly no sweat and with a smile. Can also just launch the m3u with the urls; songs' info can be auto saved... really cool =)

Regarding my comment about "scarce documentation"...  after retracing my steps back and reading page's descriptions and all that I regret it. Having used mpv for a long time, I thought that I was being a bit the devil's advocate for people that want to expand mpv's capabilities but have zero experience with the platform. Now I realize that not only it's not good to patronize the habilities of individuals but also that the info you provide is actually clear and enough and furthermore your scripts are pretty well documented with even per segment/block comments; so I'm sorry for that, I take it back.

Thank you

**Comment by jonniek** [comment]
There was a small bug of saving media titles not related to the radio that I fixed in 964dc208be3036b6619b1a5e65e2b415e2e31b45

Feel free to open another ticket if you have any feature requests or problems with my scripts in the future.
