### ISSUE TITLE
Error when pressing 'r'

### ISSUE THREAD

**Issue by nobef** [donmaiq/mpv-scripts#11]
When playing and pressing "r' such an error
![изображение](https://user-images.githubusercontent.com/77186394/212140594-0f83895b-05ca-4004-aa0f-23b8cad15f66.png)
The player also closes if you press Shift + r (R) again

**Comment by jonniek** [comment]
This means the `savepath` was not opened succesfully, did you change it to a file in your system?

Pressing shift R again will call `mp.command("stop")` which will stop playback and close the player unless idle is used. If you prefer not to have this you can remove these two lines:

https://github.com/jonniek/mpv-scripts/blob/9dbf4ddf1572e0c4c5f5569ab2690ee54166af55/radio.lua#L28-L29

**Comment by nobef** [comment]
@jonniek Thank you, everything is done. Everything works well! I did not understand then that the savepath line should also be changed. To be honest, I didn’t even know that you can save track names.
  The best script!
