### ISSUE TITLE
appendURL doesn't work on Wayland

### ISSUE THREAD

**Issue by iodream** [donmaiq/mpv-scripts#12]
Could it use [wl-clipboard](https://github.com/bugaevc/wl-clipboard) instead? 

As far as i can tell wl-paste should handle the case well where xclip is involved without any arguments but i'm not sure how to detect Wayland inside the script.

**Comment by ghost** [comment]
Are you still using this? If yes, can you test #13 ?

**Comment by iodream** [comment]
> Are you still using this? If yes, can you test #13 ?

just tested it and it works, thanks

**Comment by jonniek** [comment]
Thanks for the PR
