### ISSUE TITLE
OSC (Bottom bar with buttons) disappears after changing video through playlist

### ISSUE THREAD

**Issue by eternalcakes** [donmaiq/mpv-scripts#3]
As title. Nil issues with first video. After switching video via playlist the OSC disappears.

**Comment by eternalcakes** [comment]
Using 

a script-message osc-visibility never
b script-message osc-visibility auto

I am able to toggle OSC on the first video. After changing video via playlist it now does not allow any toggling. OSC appears to be completely disabled?

**Comment by jonniek** [comment]
Hi, can you elaborate on this step:

> After changing video via playlist

Are you talking about playlistmanager user interface?
