### ISSUE TITLE
Move to trash

### ISSUE THREAD

**Issue by kpcee** [donmaiq/mpv-scripts#4]
The current trashfileonend.lua version uses "rm" and deletes the file directly under Linux. It would be better to use the trashcan. You can do this automatically with "gio trash".

Previous version:
```
local rm = 'rm'.
local response = utils.subprocess({ cancellable=false, args = { rm, path } })
```

New version:
```
local rm = 'gio'
local response = utils.subprocess({ cancellable=false, args = { rm, "trash", path } })
```

Would have to be adjusted accordingly for Windows.

**Comment by jonniek** [comment]
Can you test 9baabcd91586375bc80844c5afe986c0b745cb58

Worked for me on windows.

**Comment by kpcee** [comment]
Just tested and works great with Arch Linux, thanks a lot!
