### ISSUE TITLE
Noob Question about the append script.

### ISSUE THREAD

**Issue by WhereAreWeSeeing** [donmaiq/mpv-scripts#6]
I am really new to using scripts at all. I wanted to ask how to specifically use the appendurl script. Does it work like `mpv -[some text related to the script]`? I couldn't find any combinations of text to use that seemed to work, but I am not sure how to use it, if this is the case. 

I ideally want to bind it to a hotkey to play whatever video is linked in my clipboard, but that is besides the point,

**Comment by jonniek** [comment]
Have you copied the lua file to your scripts directory? 

The top of the readme has some links to the mpv documentation that can help you locate it. After you have copied the appendurl lua file to your scripts directory, it will work as you described with the keybind "a". You can change this keybind by editing the last line in the lua file, or adding `a script-binding appendURL` to `input.conf` file in the mpv directory.

[Lua script reference](https://mpv.io/manual/master/#lua-scripting)

If you still have issues, let me know your operating system and the path where you saved the lua file.
