### ISSUE TITLE
Where to place m3u playlist in Windows?

### ISSUE THREAD

**Issue by nobef** [donmaiq/mpv-scripts#9]
I'm dumb and didn't understand how the script works. Maybe you need to edit the script yourself, but I could not. Please explain

**Comment by jonniek** [comment]
>Where to place m3u playlist

Can you elaborate on what you are trying to achieve

**Comment by nobef** [comment]
@jonniek ` playlist = "/home/anon/radio.m3u" --radio playlist with your channels, or url incase of 1 channel only`
 as I understand it, you need to create an m3u playlist and move it to a folder (?) And where is this "/home/anon/" in windows?
  Then I want to launch with the R key. Isn't that what they meant?

**Comment by jezokshe** [comment]
@jonniek All is well, thank you!

**Comment by jonniek** [comment]
Ok I see what you mean now.

You can change the "/home/anon/" in the lua file to a path in your windows machine. That is just a placeholder and a path in unix machines.

So create your m3u file in the file explorer anywhere you want. You can see here instructions on getting the path of that file https://www.sony.com/electronics/support/articles/00015251

Note that if your path contains \ characters, then you need to change them to \\\\ in the lua file.

So for example `"C:\users\anon\playlist.m3u"` would become `"C:\\users\\anon\\playlist.m3u"`

**Comment by nobef** [comment]
Did it like this:

`playlist = "C:\\users\\sartu\\radio.m3u" --radio playlist with your channels, or url incase of 1 channel only`

Everything is fine, it works! Thanks!

It would not hurt to write in the instructions. Perhaps that is why the script is underestimated.
